.TH "NEO4J" "1" "2022-11-14" "\ \&" "User Commands"
.SH "NAME"
neo4j \- Neo4j Server control
.SH "SYNOPSIS"
\fBneo4j\fR [\fIOPTIONS\fR]... \fICOMMAND\fR

.SH DESCRIPTION
This is a partial alias of \fBneo4j-admin\fR(1) \fBserver\fR for backwards compatability.

It is recommended to not use this command and call \fBneo4j-admin\fR(1) directly.

For information regarding Windows, see \m[blue]\fBhttps://neo4j.com/docs/operations\-manual/current/installation/windows/\fR\m[]\&.

.SH OPTIONS
.TP
\fB\-\-expand\-commands\fR
Allow command expansion in config value evaluation.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information and exit.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help text and exit.
.TP
\fB\-\-verbose\fR
Prints additional information.

.SH COMMANDS
.TP
\fBconsole\fR
Start the server as an application, running as a foreground process. Stop the server using
CTRL\-C.

.TP
\fBstart\fR
Start server as daemon, running as a background process.

.TP
\fBstop\fR
Stops a running daemonized server.

.TP
\fBrestart\fR
Restarts the server.

.TP
\fBstatus\fR
Current running state of the server.

.PP
\fBWindows\-specific commands\fR
.TP
\fBinstall\-service\fR
Installs the server as Windows service

.TP
\fBuninstall\-service\fR
Uninstalls the Windows service
.SH "FILES"
.TP
\fBconf/neo4j\&.conf\fR
Configuration.

.SH "SEE ALSO"
.BR neo4j-admin (1),
.PP
.br
Full documentation \m[blue]\fBhttps://neo4j.com/docs/operations-manual/current/\fR\m[].
