.TH "NEO4J\-ADMIN" "1" "2022-11-14" "\ \&" "User Commands"
.SH NAME
neo4j-admin \- Neo4j administration
.SH "SYNOPSIS"
.sp
\fBneo4j\-admin\fR \fICOMMAND\fR

.SH DESCRIPTION
.sp
Neo4j is a graph database, perfect for working with highly connected data. \fBneo4j\-admin\fR(1) is Neo4j\(cqs command\-line administration tool.
.sp
Please see \fBneo4j\-admin help\fR for a complete list of available commands and details of how to use them.

.SH "SEE ALSO"
.BR neo4j (1)
.PP
.br
Full documentation \m[blue]\fBhttps://neo4j.com/docs/operations-manual/current/\fR\m[].