#!/bin/bash

if [ "$1" -eq 0 ]; then
  # Uninstalling
  if [ -e "/run/systemd/system" ]; then
    systemctl stop neo4j > /dev/null 2>&1 || :
    systemctl disable --quiet neo4j > /dev/null 2>&1 || :
  else
    service neo4j stop > /dev/null 2>&1 || :
    chkconfig --del neo4j > /dev/null 2>&1 || :
  fi
fi